name: O2O Test # Name of the Catalog Entry
description: |
  O2O Test
version: # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: AM Team # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
