name: O2O # Name of the Catalog Entry
description: |
  O2O APP
version: 1.1.301 # Version of the Catalog to be used
category: soam-app # Category to be used for searching catalog entries
maintainer: AM # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
