version: '2'
.catalog:
  name: "O2O"
  version: "v1.1.301"
  description: "public service for o2o test"
  uuid: public-0
  minimum_rancher_version: v1.0.0
services:
  soam-app-o2o-fault-push:
    scale: 1
    start_on_create: true
  security:
    scale: 1
    start_on_create: true
  soam-app-o2o-ws-api:
    scale: 1
    start_on_create: true
  soam-app-o2o-fe:
    scale: 1
    start_on_create: true
  app-common-o2o:
    scale: 1
    start_on_create: true
  soam-app-o2o-web-api:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9999
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/health" "HTTP/1.0"
      reinitializing_timeout: 60000
  zuul:
    scale: 1
    start_on_create: true
  appo2o-gis-api:
    scale: 1
    start_on_create: true
  eureka-server:
    scale: 1
    start_on_create: true
  soam-app-o2o-schedule:
    scale: 1
    start_on_create: true
